# Site settings
title: DCRA Inspector App User Guide
author: 
  name: Eastbanc Technologies
  email: dcra.feedback@eastbanctech.com
description: "DCRA Inspector App User Guide"

# Build settings
remote_theme: jekyll/minima 
minima:
  Skin: dark 
