# Site settings
title: DCRA Dispatch App User Guide
author: 
  name: Eastbanc Technologies
  email: dcra.feedback@eastbanctech.com
description: "DCRA Dispatch App User Guide"

# Build settings
remote_theme: jekyll/minima 

